config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search", views.search, name="search"),
]

rooms/models.py
from django.db import models
from django_countries.fields import CountryField
from django.urls import reverse
from core import models as core_models
from users import models as user_models

# Create your models here.


class AbstactItem(core_models.TimeStampedModel):

    """ Abstact Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstactItem):
    pass

    class Meta:
        verbose_name = "Room Type"
        ordering = ["created"]


class Amenity(AbstactItem):
    pass

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstactItem):
    pass

    class Meta:
        verbose_name_plural = "Facilities"


class House_rules(AbstactItem):
    pass

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):
    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")

    """ 이렇게도 사용가능 """
    room = models.ForeignKey("Room", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):
    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    contry = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(user_models.User, on_delete=models.CASCADE)
    room_type = models.ForeignKey(RoomType, on_delete=models.SET_NULL, null=True)
    amenities = models.ManyToManyField(Amenity, blank=True)
    facilities = models.ManyToManyField(Facility, blank=True)
    house_rules = models.ManyToManyField(House_rules, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0

        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return all_ratings / len(all_reviews)
        return 0

rooms/views.py
from django.db.models import ObjectDoesNotExist
from django.http import Http404
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView
from django_countries import Countries
from . import models

# Create your views here.
class HomeView(ListView):

    """ HomeView Definition """

    model = models.Room
    paginate_by = 10
    ordering = ["pk"]


class RoomDetail(DetailView):
    model = models.Room


def search(request):

    city = request.GET.get("city", "")
    city = str.capitalize(city)
    country = request.GET.get("country")
    room_type = int(request.GET.get("room_type",0))
    room_types = models.RoomType.objects.all()
    price = int(request.GET.get("price",0))
    guests = int(request.GET.get("guests",0))
    beds = int(request.GET.get("beds",0))
    bedrooms = int(request.GET.get("bedrooms",0))
    baths = int(request.GET.get("baths",0))
    instant = request.GET.get("instant", False)
    super_host = request.GET.get("super_host",False)
    s_amenities = request.GET.getlist("amenities")
    s_facilities = request.GET.getlist("facilities")

    form = {"city": city,
            "s_room_type": room_type,
            "s_country": country,
            "price": price,
            "guests": guests,
            "beds": beds,
            "bedrooms": bedrooms,
            "baths": baths,
            "s_amenities": s_amenities,
            "s_facilities": s_facilities,
            "instant": instant,
            "super_host": super_host,
            }

    room_types = models.RoomType.objects.all()
    amenities = models.Amenity.objects.all()
    facilities = models.Facility.objects.all()

    choices = {"countries": Countries, "room_types": room_types, "amenities" : amenities, "facilities" : facilities}

    return render(request, "rooms/search.html", {**form, **choices},)

templates/rooms/room_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{% block content %}
    <div>
        <h1>{{room.name}}</h1>
        <h3>{{room.description}}</h3>
    <div>
    <div>
        <h2>By : {{room.host.username}}
            {% if room.host.superhost %}
                (superhost)
            {% endif %}
        <h2>

        <h3>Amenities</h3>
        <ul>
        {% for a in room.amenities.all %}
            <li>{{a}}</li>
        {% endfor %}
        </ul>

        <h3>Facilities</h3>
        <ul>
        {% for f in room.facilities.all %}
            <li>{{f}}</li>
        {% endfor %}
        </ul>

        <h3>House Rule</h3>
        <ul>
        {% for f in room.house_rules.all %}
            <li>{{f}}</li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/rooms/room_list.html
{% extends "base.html" %}

{% block page_title %}
    home 
{% endblock page_title %}

{% block content %}
    {% for room in object_list%}
        <h4>
        <a href="{% url "rooms:detail" room.pk %}">{{room.name}} / ${{room.price}}</a>
        </h4>
    {% endfor%} 
    
    {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}
    page : {{page_obj.number}} / {{page_obj.paginator.num_pages}}
    {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <h2>Search!!</h2>
    <form method="get", action=" {% url "rooms:search" %}">
        <div>
            <label for="city">City</label>
            <input value="{{city}}" id="city" name="city" placeholder="Search By City"/>
        </div>

        <div>
            <label for="country">country</label>
            <select id="country" name="country">
                {% for country in countries %}
                    <option value="{{country.code}}" {% if country.code == s_country %} selected {%endif%}>{{country.name}}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="room_type">Room Type</label>
            <select id="room_type" name="room_type">
                <option value="0" {% if s_room_type == 0 %} selected {% endif %}>Any kind</option>
                {% for room_type in room_types %}
                    <option value="{{room_type.pk}}" {% if room_type.pk == s_room_type %} selected {% endif %}>{{room_type.name}}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="price">Price</label>
            <input value="{{price}}" type="number" name="price" id="price" placeholder="Price">
        </div>

        <div>
            <label for="guests">Guests</label>
            <input value="{{guests}}"type="number" name="guests" id="guests" placeholder="Guests">
        </div>

        <div>
            <label for="beds">Beds</label>
            <input value="{{beds}}" type="number" name="beds" id="beds" placeholder="Beds">
        </div>

        <div>
            <label for="bedrooms">Bedrooms</label>
            <input value="{{bedrooms}}" type="number" name="bedrooms" id="bedrooms" placeholder="Bedrooms">
        </div>

        <div>
            <label for="baths">Baths</label>
            <input value="{{baths}}"type="number" name="baths" id="baths" placeholder="Baths">
        </div>

        <div>
            <label for="instant">Instant book only?</label>
            <input type="checkbox" name="instant" id="instant" {% if instant %} checked {% endif %}>
        </div>

        <div>
            <label for="super_host">By super host only?</label>
            <input type="checkbox" name="super_host" id="super_host" {% if super_host %} checked {% endif %}>
        </div>

        <div>
            <h3>Amenities</h3>
            <ul>
                {% for amenity in amenities %}
                <li>
                    <label for="a_{{amenity.pk}}">{{amenity.name}}</label>
                    <input type="checkbox" 
                    id="a_{{amenity.pk}}" 
                    name="amenities" 
                    value="{{amenity.pk}}"
                    {% if amenity.pk|slugify in s_amenities%}
                        checked
                    {% endif %}
                    >
                </li>
                {% endfor %}
            </ul>
        </div>

        <div>
            <h3>Facilities</h3>
            <ul>
                {% for facility in facilities %}
                <li>
                    <label for="a_{{facility.pk}}">{{facility.name}}</label>
                    <input type="checkbox" 
                    id="a_{{facility.pk}}" 
                    name="facilities" 
                    value="{{facility.pk}}"
                    {% if facility.pk|slugify in s_facilities%}
                        checked
                    {% endif %}
                    >
                </li>
                {% endfor %}
            </ul>
        </div>
        
        

        <button>submit</button>
    </form>
    Searching By {{city}}
{% endblock content %}